pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get update
  displayName: 'Add APT repositories'

- script: |
    sudo apt-get install -y \
      g++-8 \
      gcc-8 \
      libgmp-dev \
      ninja-build

    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 40
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 40
  displayName: 'Install C build tools'

- script: >
    curl -L https://www.stackage.org/stack/linux-x86_64 |
    sudo tar xz --wildcards --strip-components=1 -C /usr/local/bin '*/stack'
  displayName: 'Install Haskell Stack'

- script: stack --no-terminal setup
  displayName: 'Install GHC'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
