resolver: lts-12.13

require-stack-version: '>= 1.6'

packages:
  - compiler
  - intentioc
  - prelude
  - syntax
  - test-runner
  - test-utils

extra-deps:
  - haskell-exp-parser-0.1.1
  - megaparsec-7.0.4
  - neat-interpolation-0.3.2.4

flags:
  language-c-quote:
    full-haskell-antiquotes: false
