resolver: lts-12.5

require-stack-version: '>= 1.6'

packages:
  - src/intentio-codegen
  - src/intentio-core
  - src/intentio-driver
  - src/intentio-hir
  - src/intentio-syntax
  - src/intentio-testutil

extra-deps:
  - haskell-exp-parser-0.1.1

flags:
  language-c-quote:
    full-haskell-antiquotes: false
