resolver: lts-12.5

require-stack-version: '>= 1.6'

packages:
  - compiler
  - intentioc
  - prelude
  - syntax
  - test-utils

extra-deps:
  - haskell-exp-parser-0.1.1

flags:
  language-c-quote:
    full-haskell-antiquotes: false
