_common: !include "../package-common.yaml"

name: intentio-codegen

<<: *meta

dependencies:
  - aeson
  - base
  - containers
  - intentio-core
  - intentio-hir
  - language-c-quote
  - mainland-pretty
  - mtl
  - neat-interpolation
  - text

library:
  source-dirs: src

tests:
  intentio-codegen-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - intentio-codegen
      - hspec
      - QuickCheck
