_common: !include "../package-common.yaml"

name: intentio-prelude

<<: *meta

dependencies:
  - aeson
  - base
  - containers
  - convertible
  - lens
  - mtl
  - protolude
  - text
  - transformers
  - unordered-containers

library:
  source-dirs: src
