_common: !include "../package-common.yaml"

name: intentio-compiler

<<: *meta

dependencies:
  - aeson
  - base
  - containers
  - directory
  - filepath
  - intentio-prelude
  - intentio-syntax
  - language-c-quote
  - mainland-pretty
  - megaparsec
  - mtl
  - neat-interpolation
  - srcloc
  - text
  - transformers
  - typed-process

library:
  source-dirs: src

tests:
  intentio-core-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - intentio-compiler
      - hspec
      - QuickCheck
