_common: !include "../package-common.yaml"

name: intentio-driver

<<: *meta

dependencies:
  - aeson
  - base
  - filepath
  - intentio-core
  - intentio-syntax
  - optparse-applicative

library:
  source-dirs: src

executables:
  intentioc:
    main: Main.hs
    source-dirs: app
    dependencies:
      - intentio-driver

tests:
  intentio-driver-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - intentio-driver
      - hspec
