_common: !include "../package-common.yaml"

name: test-runner

<<: *meta

dependencies:
  - aeson
  - base
  - containers
  - Diff
  - directory
  - filepath
  - intentio-prelude
  - mmorph
  - mtl
  - optparse-applicative
  - text
  - transformers
  - typed-process
  - unordered-containers
  - yaml

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - test-runner

tests:
  test-runner-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - test-runner
      - hspec
