_common: !include "../package-common.yaml"

name: intentio-testutil

<<: *meta

dependencies:
  - base
  - directory
  - filepath
  - hspec
  - intentio-core
  - pretty-simple
  - text

library:
  source-dirs: src
