_common: !include "../package-common.yaml"

name: intentio-syntax

<<: *meta

dependencies:
  - base
  - bimap
  - convertible
  - filepath
  - intentio-core
  - megaparsec
  - text
  - unordered-containers

library:
  source-dirs: src

tests:
  intentio-syntax-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - intentio-syntax
      - intentio-testutil
